In [1]:
#1 import numpy as np and version
import numpy as np
np.__version__

'1.14.3'

In [16]:
#2 create a 1D array
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#3 create a boolean array
np.full((3,3), True, dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
#4 extract items which satisfy a given condition
arr_4 = arr[arr%2 == 1]
print(arr_solution)

[1 3 5 7 9]


In [22]:
#5 replace items that satisgy a condition
arr[arr%2 == 1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
#6 5.without affecting the original array
arr = np.array(range(10))
arr_6 = np.where(arr%2 == 1, -1, arr)
print(arr)
arr_6

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [29]:
#reshape a array
arr.reshape(2, -1)
#Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
#8 stack two arrays vertically
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
#9 stack horizontally
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [37]:
#10 custom sequences
arr_10 = np.array([1, 2, 3])
arr10 = np.r_[np.repeat(arr_10, 3), np.tile(arr_10, 3)]
arr10

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [38]:
#11 get the common items
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])